services:
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    hostname: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ../minio-data:/data
  spark-base:
    build:
      context: .
      dockerfile: Dockerfile.spark-base
    image: spark-base:latest
    develop:
      watch:
        - path: ./Dockerfile.spark-base
          action: rebuild
  spark-master:
    image: spark-base:latest
    depends_on:
      - spark-base
    container_name: spark-master
    hostname: spark-master
    command: >
      /opt/spark/sbin/start-master.sh &&
      tail -f /dev/null
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_NO_DAEMONIZE: "true"
      HADOOP_OPTIONAL_TOOLS: hadoop-aws

  spark-worker-1:
    image: spark-base:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    command: >
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /dev/null
    ports:
      - "8081:8081"
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "1g"
      HADOOP_OPTIONAL_TOOLS: hadoop-aws

  spark-worker-2:
    image: spark-base:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    command: >
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /dev/null
    ports:
      - "8082:8081"
    environment:
      SPARK_NO_DAEMONIZE: "true"
      SPARK_WORKER_CORES: "1"
      SPARK_WORKER_MEMORY: "1g"
      HADOOP_OPTIONAL_TOOLS: hadoop-aws

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    develop:
      watch:
        - path: ./Dockerfile.jupyter
          action: rebuild
    container_name: jupyter
    hostname: jupyter
    # Ensures spark-base is built before Jupyter (FROM spark-base:latest is local, not Docker Hub).
    depends_on:
      spark-base:
        condition: service_started
      spark-master:
        condition: service_started
      spark-worker-1:
        condition: service_started
      spark-worker-2:
        condition: service_started
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ../notebooks:/home/jovyan/work
      - ../jupyter-data:/home/jovyan/data
    environment:
      HADOOP_OPTIONAL_TOOLS: hadoop-aws
      SPARK_MASTER: spark://spark-master:7077
      PYSPARK_SUBMIT_ARGS: >
        --conf spark.driver.host=jupyter
        pyspark-shell
